/*
 * DO NOT EDIT -- generated by the Makefile
 */


#if !defined(CALC_HAVE_GETTIME_H)
#define CALC_HAVE_GETTIME_H


/* do we have or want clock_gettime()? */
#undef HAVE_GETTIME /* no - no SGI_CYCLE and no REALTIME */


#endif /* !CALC_HAVE_GETTIME_H */
